# Analyse de la qualité des jeux de données

### Créer une fonction qui produit les informations suivantes pour un data frame :
- la taille,
- le typage,
- le pourcentage de null.

In [45]:
## Rediriger la racine du notebooks au dossier Projet_perso ###
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))
#############################################################

import pandas as pd
from python_scripts.DB_link import engine

In [ ]:
def quality_report(df, col_min_max, col_mode, col_mean_med):
    """
    Génère un rapport de qualité d'un DataFrame.
    """
    if len(col_mode) > 0:
        report = pd.DataFrame({
            "Colonne": df.columns,
            "Type": df.dtypes.astype(str).values,
            "Non nuls": df.notna().sum().values,
            "% Null": (df.isna().mean() * 100).round(2).values,
            "Distincts": df.nunique(dropna=True).values,
            "% Distincts": ((df.nunique(dropna=True) / len(df)) * 100).round(2).values,
            "Mode": [
                df[col].mode().iloc[0] if col in col_mode else "-"
                for col in df.columns
            ]
        })
    else:
        report = pd.DataFrame({
            "Colonne": df.columns,
            "Type": df.dtypes.astype(str).values,
            "Non nuls": df.notna().sum().values,
            "% Null": (df.isna().mean() * 100).round(2).values,
            "Distincts": df.nunique(dropna=True).values,
            "% Distincts": ((df.nunique(dropna=True) / len(df)) * 100).round(2).values,
        })

    if len(col_min_max) > 0:
        # Colonnes numériques
        report["Min"] = [df[col].min() if col in col_min_max else "-" for col in df.columns]

        report["Max"] = [
            df[col].max() if col in col_min_max else "-"
            for col in df.columns
        ]
    if len(col_mean_med) > 0:
        report["Moyenne"] = [
            round(df[col].mean(), 2) if col in col_mean_med else "-"
            for col in df.columns
        ]

        report["Médiane"] = [
            round(df[col].median(), 2) if col in col_mean_med else "-"
            for col in df.columns
        ]

    return report

In [47]:
accidents = pd.read_sql_table("accidents", schema="silver", con=engine)

columns_for_mode = [
    'GEO_region', 'GEO_province', 'GEO_commune', 'COND_carrefour', 'COND_meteo', 'COND_route', 'COND_agglomeration',
    'COND_lumiere', 'COND_type_route', 'ACC_etat_victimes','ACC_vehicule_1', 'ACC_vehicule_2', 'ACC_collision_type',
    'COND_obstacles', 'ACC_nom_autoroute', 'COND_routes_largeur_cat'
]

columns_for_min_max = [
    'COND_densite', 'SOIN_min_distance'
]

quality_report(accidents, columns_for_min_max, columns_for_mode, columns_for_min_max)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Mode,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,289466,0.00,581,0.20,-,-,-,-,-
1,GEO_region,str,289466,0.00,3,0.00,Région flamande,-,-,-,-
2,GEO_province,str,289466,0.00,11,0.00,Province d’Anvers,-,-,-,-
3,GEO_commune,str,289466,0.00,581,0.20,anvers,-,-,-,-
4,COND_carrefour,str,289466,0.00,3,0.00,Hors carrefour,-,-,-,-
5,COND_meteo,str,289466,0.00,16,0.01,Normales,-,-,-,-
6,COND_route,str,289466,0.00,13,0.00,Sec,-,-,-,-
7,COND_agglomeration,str,289466,0.00,3,0.00,En agglomération,-,-,-,-
8,COND_lumiere,str,289466,0.00,6,0.00,Jour,-,-,-,-
9,COND_type_route,str,289466,0.00,4,0.00,Route régionale,-,-,-,-
10,ACC_etat_victimes,str,289466,0.00,4,0.00,Avec blessé(s) leger(s),-,-,-,-
11,ACC_vehicule_1,str,289466,0.00,10,0.00,Voiture,-,-,-,-
12,ACC_vehicule_2,str,289466,0.00,12,0.00,Voiture,-,-,-,-
13,ACC_collision_type,str,289466,0.00,10,0.00,Entre 2 conducteurs: Par le côté (avant/derriè...,-,-,-,-
14,COND_obstacles,str,289466,0.00,23,0.01,Pas d’obstacle,-,-,-,-
15,DT_date,datetime64[us],289466,0.00,2307,0.80,-,-,-,-,-
16,ID,int64,289466,0.00,289466,100.00,-,-,-,-,-
17,ACC_nom_autoroute,str,14063,95.14,43,0.01,R0,-,-,-,-
18,COND_routes_largeur_cat,str,244823,15.42,5,0.00,moyen,-,-,-,-
19,COND_densite,float64,253619,12.38,18969,6.55,-,0.0,2.380131,0.43,0.34
20,SOIN_min_distance,float64,253619,12.38,210891,72.86,-,2.538757,18195708177893552.0,100544468115.770004,2325.16
21,GEO_longitude,float64,253619,12.38,210888,72.85,-,-,-,-,-
22,GEO_latitude,float64,253619,12.38,210882,72.85,-,-,-,-,-

In [54]:
population = {}
for year in range(2017, 2025):
    population[f"population_{year}"] = pd.read_sql_table(f"population_{year}", schema="silver", con=engine)

In [55]:
columns_for_mode = []

for year in range(2017, 2025):
    print(f"Report for data frame population ({year})")
    display(quality_report(population[f"population_{year}"], [], columns_for_mode, []))

Report for data frame population (2017)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,462780,0.0,589,0.13,-,-,-,-
1,GEO_commune,str,462780,0.0,589,0.13,-,-,-,-
2,GEO_province,str,462780,0.0,11,0.00,-,-,-,-
3,GEO_region,str,462780,0.0,3,0.00,-,-,-,-
4,P_sexe,str,462780,0.0,2,0.00,-,-,-,-
5,P_etat_civil,str,462780,0.0,4,0.00,-,-,-,-
6,P_age,int64,462780,0.0,101,0.02,-,-,-,-
7,P_nbr_individus,int64,462780,0.0,1119,0.24,-,-,-,-
8,DT_annee,int64,462780,0.0,1,0.00,-,-,-,-

Report for data frame population (2018)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,465418,0.0,589,0.13,-,-,-,-
1,GEO_commune,str,465418,0.0,589,0.13,-,-,-,-
2,GEO_province,str,465418,0.0,11,0.00,-,-,-,-
3,GEO_region,str,465418,0.0,3,0.00,-,-,-,-
4,P_sexe,str,465418,0.0,2,0.00,-,-,-,-
5,P_etat_civil,str,465418,0.0,4,0.00,-,-,-,-
6,P_age,int64,465418,0.0,101,0.02,-,-,-,-
7,P_nbr_individus,int64,465418,0.0,1115,0.24,-,-,-,-
8,DT_annee,int64,465418,0.0,1,0.00,-,-,-,-

Report for data frame population (2019)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,463381,0.0,581,0.13,-,-,-,-
1,GEO_commune,str,463381,0.0,581,0.13,-,-,-,-
2,GEO_province,str,463381,0.0,11,0.00,-,-,-,-
3,GEO_region,str,463381,0.0,3,0.00,-,-,-,-
4,P_sexe,str,463381,0.0,2,0.00,-,-,-,-
5,P_etat_civil,str,463381,0.0,4,0.00,-,-,-,-
6,P_age,int64,463381,0.0,101,0.02,-,-,-,-
7,P_nbr_individus,int64,463381,0.0,1102,0.24,-,-,-,-
8,DT_annee,int64,463381,0.0,1,0.00,-,-,-,-

Report for data frame population (2020)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,465657,0.0,581,0.12,-,-,-,-
1,GEO_commune,str,465657,0.0,581,0.12,-,-,-,-
2,GEO_province,str,465657,0.0,11,0.00,-,-,-,-
3,GEO_region,str,465657,0.0,3,0.00,-,-,-,-
4,P_sexe,str,465657,0.0,2,0.00,-,-,-,-
5,P_etat_civil,str,465657,0.0,4,0.00,-,-,-,-
6,P_age,int64,465657,0.0,101,0.02,-,-,-,-
7,P_nbr_individus,int64,465657,0.0,1100,0.24,-,-,-,-
8,DT_annee,int64,465657,0.0,1,0.00,-,-,-,-

Report for data frame population (2021)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,467027,0.0,581,0.12,-,-,-,-
1,GEO_commune,str,467027,0.0,581,0.12,-,-,-,-
2,GEO_province,str,467027,0.0,11,0.00,-,-,-,-
3,GEO_region,str,467027,0.0,3,0.00,-,-,-,-
4,P_sexe,str,467027,0.0,2,0.00,-,-,-,-
5,P_etat_civil,str,467027,0.0,4,0.00,-,-,-,-
6,P_age,int64,467027,0.0,101,0.02,-,-,-,-
7,P_nbr_individus,int64,467027,0.0,1096,0.23,-,-,-,-
8,DT_annee,int64,467027,0.0,1,0.00,-,-,-,-

Report for data frame population (2022)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,469719,0.0,581,0.12,-,-,-,-
1,GEO_commune,str,469719,0.0,581,0.12,-,-,-,-
2,GEO_province,str,469719,0.0,11,0.00,-,-,-,-
3,GEO_region,str,469719,0.0,3,0.00,-,-,-,-
4,P_sexe,str,469719,0.0,2,0.00,-,-,-,-
5,P_etat_civil,str,469719,0.0,4,0.00,-,-,-,-
6,P_age,int64,469719,0.0,101,0.02,-,-,-,-
7,P_nbr_individus,int64,469719,0.0,1121,0.24,-,-,-,-
8,DT_annee,int64,469719,0.0,1,0.00,-,-,-,-

Report for data frame population (2023)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,474209,0.0,581,0.12,-,-,-,-
1,GEO_commune,str,474209,0.0,581,0.12,-,-,-,-
2,GEO_province,str,474209,0.0,11,0.00,-,-,-,-
3,GEO_region,str,474209,0.0,3,0.00,-,-,-,-
4,P_sexe,str,474209,0.0,2,0.00,-,-,-,-
5,P_etat_civil,str,474209,0.0,4,0.00,-,-,-,-
6,P_age,int64,474209,0.0,101,0.02,-,-,-,-
7,P_nbr_individus,int64,474209,0.0,1108,0.23,-,-,-,-
8,DT_annee,int64,474209,0.0,1,0.00,-,-,-,-

Report for data frame population (2024)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,476319,0.0,581,0.12,-,-,-,-
1,GEO_commune,str,476319,0.0,581,0.12,-,-,-,-
2,GEO_province,str,476319,0.0,11,0.00,-,-,-,-
3,GEO_region,str,476319,0.0,3,0.00,-,-,-,-
4,P_sexe,str,476319,0.0,2,0.00,-,-,-,-
5,P_etat_civil,str,476319,0.0,4,0.00,-,-,-,-
6,P_age,int64,476319,0.0,101,0.02,-,-,-,-
7,P_nbr_individus,int64,476319,0.0,1108,0.23,-,-,-,-
8,DT_annee,int64,476319,0.0,1,0.00,-,-,-,-

In [56]:
occupation_sol = pd.read_sql_table("occupation_par_commune", schema="silver", con=engine)

columns_for_min_max = ['OCC_% Autres', 'Eaux',
       'Total', 'OCC_% Total terrains bâtis', 'OCC_% Autres terrains bâtis',
       'Terrains commerciaux', 'Terrains industriels', 'Terrains résidentiels',
       'OCC_% Terrains agricoles', 'OCC_% Terrains forestiers']

quality_report(occupation_sol, columns_for_min_max, [], columns_for_min_max)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,4648,0.0,581,12.50,-,-,-,-
1,GEO_commune,str,4648,0.0,580,12.48,-,-,-,-
2,DT_annee,int64,4648,0.0,8,0.17,-,-,-,-
3,OCC_% Autres,float64,4648,0.0,1,0.02,0.0,0.0,0.0,0.0
4,Eaux,float64,4648,0.0,1,0.02,0.0,0.0,0.0,0.0
5,Total,float64,4648,0.0,2389,51.40,114.2297,21534.1913,5278.64,4066.6
6,OCC_% Total terrains bâtis,float64,4648,0.0,4640,99.83,4.602268,99.154194,27.55,22.78
7,OCC_% Autres terrains bâtis,float64,4648,0.0,4644,99.91,2.376609,52.670256,12.13,9.44
8,Terrains commerciaux,float64,4648,0.0,4348,93.55,0.1085,339.1408,26.27,16.33
9,Terrains industriels,float64,4648,0.0,4322,92.99,0.0,4158.1973,101.58,45.27
10,Terrains résidentiels,float64,4648,0.0,4642,99.87,3.7139,3228.8799,478.08,383.99
11,OCC_% Terrains agricoles,float64,4648,0.0,1,0.02,0.0,0.0,0.0,0.0
12,OCC_% Terrains forestiers,float64,4648,0.0,3596,77.37,0.0,73.54049,14.22,7.78

In [61]:
revenus = {}
for year in range(2017, 2024):
    revenus[f"revenus_{year}"] = pd.read_sql_table(f"revenus_{year}", schema="silver", con=engine)

columns_for_mode = []

columns_for_min_max = ['REV_pourcentage_manquant', 'REV_median', 'REV_risque_pauvrete']

for year in range(2017, 2024):
    print(f"Report for data rame revenus ({year})")
    display(quality_report(revenus[f"revenus_{year}"], columns_for_min_max, columns_for_mode, columns_for_min_max))

Report for data rame revenus (2017)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,580,0.00,580,100.00,-,-,-,-
1,GEO_commune,str,580,0.00,580,100.00,-,-,-,-
2,REV_pourcentage_manquant,float64,580,0.00,58,10.00,0.005,0.158,0.02,0.01
3,REV_median,float64,579,0.17,555,95.69,15086.16,34080.99,23864.77,24137.82
4,REV_risque_pauvrete,float64,579,0.17,579,99.83,0.0383,0.40703,0.09,0.08

Report for data rame revenus (2018)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,580,0.00,580,100.00,-,-,-,-
1,GEO_commune,str,580,0.00,580,100.00,-,-,-,-
2,REV_pourcentage_manquant,float64,580,0.00,59,10.17,0.005,0.154,0.02,0.01
3,REV_median,float64,579,0.17,564,97.24,15799.66,35668.23,24789.88,25074.1
4,REV_risque_pauvrete,float64,579,0.17,579,99.83,0.039095,0.395502,0.09,0.08

Report for data rame revenus (2019)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,580,0.00,580,100.00,-,-,-,-
1,GEO_commune,str,580,0.00,580,100.00,-,-,-,-
2,REV_pourcentage_manquant,float64,580,0.00,61,10.52,0.004,0.153,0.02,0.01
3,REV_median,float64,579,0.17,562,96.90,16663.61,36810.44,25689.63,26007.19
4,REV_risque_pauvrete,float64,579,0.17,579,99.83,0.038747,0.377007,0.1,0.08

Report for data rame revenus (2020)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,580,0.0,580,100.00,-,-,-,-
1,GEO_commune,str,580,0.0,580,100.00,-,-,-,-
2,REV_pourcentage_manquant,float64,580,0.0,51,8.79,0.005,0.129,0.02,0.01
3,REV_median,float64,580,0.0,561,96.72,17398.575,38312.93,26354.24,26660.8
4,REV_risque_pauvrete,float64,580,0.0,580,100.00,0.038412,0.361351,0.09,0.08

Report for data rame revenus (2021)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,580,0.0,580,100.00,-,-,-,-
1,GEO_commune,str,580,0.0,580,100.00,-,-,-,-
2,REV_pourcentage_manquant,float64,580,0.0,54,9.31,0.003,0.121,0.02,0.01
3,REV_median,float64,580,0.0,569,98.10,18350.1,39626.74,27024.07,27339.94
4,REV_risque_pauvrete,float64,580,0.0,580,100.00,0.031359,0.336891,0.08,0.07

Report for data rame revenus (2022)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,580,0.0,580,100.00,-,-,-,-
1,GEO_commune,str,580,0.0,580,100.00,-,-,-,-
2,REV_pourcentage_manquant,float64,580,0.0,54,9.31,0.005,0.128,0.02,0.01
3,REV_median,float64,580,0.0,562,96.90,19258.33,41565.23,28296.52,28615.86
4,REV_risque_pauvrete,float64,580,0.0,578,99.66,0.03308,0.330881,0.08,0.07

Report for data rame revenus (2023)

,Colonne,Type,Non nuls,% Null,Distincts,% Distincts,Min,Max,Moyenne,Médiane
0,GEO_commune_REFNIS,int64,580,0.0,580,100.00,-,-,-,-
1,GEO_commune,str,580,0.0,580,100.00,-,-,-,-
2,REV_pourcentage_manquant,float64,580,0.0,52,8.97,0.005,0.129,0.02,0.01
3,REV_median,float64,580,0.0,562,96.90,20862.44,44065.97,30615.92,30951.48
4,REV_risque_pauvrete,float64,580,0.0,580,100.00,0.033717,0.328332,0.08,0.07